name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:

    strategy:
      matrix:
        os: 
          - macos-latest
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Setup Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: 3.9
        cache: pip
        check-latest: true
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Compile with Nuitka
      uses: Nuitka/Nuitka-Action@main
      with:
        nuitka-version: main
        script-name: main
        standalone: true
        onefile: true
        python-flag: |
          isolated
          -O
          no_docstrings
          -S
        show-scons: true
        enable-plugins: anti-bloat,implicit-imports,numpy,tk-inter
    - name: Archive build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: built-files-${{ matrix.os }}
        path: build
