name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:

    strategy:
      matrix:
        os: 
          - macos-latest
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Setup Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: 3.9
        check-latest: true
    - name: Install dependencies
      run: |
        pip install -U pip
        pip install -U -r requirements.txt
    - name: Compile with Nuitka
      uses: Nuitka/Nuitka-Action@v1.1
      with:
        nuitka-version: main
        script-name: main.py
        standalone: true
        onefile: true
        # isolated: 孤立モード
        # -O: assert無効
        # no_docstrings: docstring無効
        # -S: siteモジュール無効
        python-flag: |
          isolated
          -O
          no_docstrings
          -S
        # show-scons: true
        enable-plugins: anti-bloat,implicit-imports,numpy,tk-inter
    - name: Archive build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: built-files-${{ matrix.os }}
        path: build
        compression-level: 9
